### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by cdExpat** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#1]
Hi BigBobbas, thanks for your  hard work. It's working very good.

When installing I missed some files. The font "DSEG14Classic-Regular.ttf" is not available in your repositry (font files), nor could i find the s3d.zip file you mentioned in your instructions.

Off course I was able to compile your yaml file, this issue is just to inform you. BTW, You also did a great job for the documentation.

**Comment by BigBobbas** [comment]
> Hi BigBobbas, thanks for your hard work. It's working very good.
> 
> When installing I missed some files. The font "DSEG14Classic-Regular.ttf" is not available in your repositry (font files), nor could i find the s3d.zip file you mentioned in your instructions.
> 
> Off course I was able to compile your yaml file, this issue is just to inform you. BTW, You also did a great job for the documentation.

Hi , thank you for the feedback, It is still a work in progress, but almost finished. i had to open the repo up as I need to test access for importing the config into the ESPHome Dashboard. Hopefully that will be finished today / tomorrow. There will also be a web installer to install the firmware and adopt the device into the dashboard with it's full config. 
I'll check out the points you mentioned with regards to the fonts and the zip i will pop back up :)
I still need to add a few pics and some tidying and re-capping of the docs as a few bits have changed, over the last few days.
Cheers 
Rob
