### ISSUE TITLE
simple request

### ISSUE THREAD

**Issue by sudoxnym** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#108]
any way to easily turn all of celsius to fahrenheit? im in a country that refuses to teach the proper measurements. love the project by the way

**Comment by BigBobbas** [comment]
Hi there,
unfortunatley i'm not aware that it can be done globally but you can add the following filter to a sensor to do the conversion.
```yaml
filters:
  - lambda: return x * (9.0/5.0) + 32.0;
```
you can also add 'unit_of_measurement: "°F"`

**Comment by sudoxnym** [comment]
Thank you for the math.I wasn't able to find where the icon for climate is getting it's reading on the idle page though, i was able to find where the sleep screen does it, but not the climate icon which is mainly what I was needing.

**Comment by sudoxnym** [comment]
closing
