### ISSUE TITLE
No unique id for entitity screensaver_mode

### ISSUE THREAD

**Issue by Lin4fun** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#12]
Hi,

Thank you for the brilliant job. I am very thanksfull for your code!
If the same code is used on several s3 boxes homeassistant is going to full load until reboot. As soon as one device is used tge oisd is hiing up again to 100%.

Device name and friendly name is of course different for each device.
I tried to ad 4 digids of the mac adress to correct the issue but my knowledge is dtill in beginner state so I messed it up.
How to fix this problem?

Homeassistant is loghing the following error message in mainlog: 
[Logger: homeassistant.components.switch
Quelle: helpers/entity_platform.py:766
Integration: Schalter (Dokumentation, Probleme)
Erstmals aufgetreten: 11:37:03 (1 Vorkommnisse)
Zuletzt protokolliert: 11:37:03

Platform esphome does not generate unique IDs. ID 3C:84:27:05:9B:78-switch-screensaver_mode is already used by switch.terminal1_1bedroom2_screensaver_mode - ignoring switch.terminal1-1bedroom2_screensaver_mode]

Br,
Thomas

**Comment by youkorr** [comment]
Bonsoir est-ce cette erreur ce fait pendant la compilation si oui avez-vous fait un clean build

**Comment by BigBobbas** [comment]
thank you for making me aware of the issue, I will look into this for you.

If each device has a unique `name:` flashed to the device, then this shouldn't happen.

You can try to delete all s3box entries from the ESPHome integration in HA >> settings>> devices and services>>esphome
and then re-add them. to see if that helps.

However I will also test.

Many Thanks
Rob

**Comment by Lin4fun** [comment]
> thank you for making me aware of the issue, I will look into this for you.
> 
> If each device has a unique `name:` flashed to the device, then this shouldn't happen.
> 
> You can try to delete all s3box entries from the ESPHome integration in HA >> settings>> devices and services>>esphome and then re-add them. to see if that helps.
> 
> However I will also test.
> 
> Many Thanks Rob

Hi,

It was clean install every time. I also deleted them from the integration side.
But may i should mention that i crested the config manuell and build from esphome as my esphome addon strangly stoped a while ago with adopting devices, regardless if they were in same subnet or not.

I noticed this behavior early also in other projects. Even if names (friendly- as well the hostname was different) Some time ago Homeassistant / Esphome came with warnings regarding unique id's. 
May the best ist to use partly the mac adress to make it unique. That is at least accepted if i remember right.

**Comment by BigBobbas** [comment]
HA will only use the device name to connect to the ESP, the friendly_name: isn't considered. The devicename will be the host name for HA to connect using mDNS. Therefore this name needs to be unique to each device. 

When manually creating the config and uploading to the device , it is also important to make sure that the device that you are uploading the firmware to, is the correct device based on the device name & MAC address. (you may need to check your router to see what IP is assigned to which MAC. if you ping devicename.local this should resolve to the correct IP address of the device.

**Comment by Lin4fun** [comment]
I do flash the initial config always through usb connection, direct connected to the HA server or through webserial. I started no all over again to check this behavior one more time. May it was cause by something other strange thing. I'll post feedback.

**Comment by BigBobbas** [comment]
are you still having an issue with this ? 
Thanks

Rob

**Comment by Lin4fun** [comment]
Hi Rob!

looks like it disappeared after I recompiled with new config from a later version.
I did that on all 3 terminals I have.
I think you can close this isseu. If it comes up one more time I'll reopen with more details.

Thx!
