### ISSUE TITLE
ADD IR Blaster config by @Almostinteractive

### ISSUE THREAD

**Issue by BigBobbas** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#16]
incorporate the IR Blaster feature developed by @Almostinteractive
https://github.com/AlmostInteractive/ESP32-S3-Box3-IR-Blaster-Learning-Example

**Comment by youkorr** [comment]
do you think about integrating it later it would be nice for my air conditioning and tv

**Comment by BigBobbas** [comment]
moved to todo https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/issues/49
