### ISSUE TITLE
Tidy yaml and add substitutions where possible

### ISSUE THREAD

**Issue by BigBobbas** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#17]
look at ways to improve customisation with substitutions - possibly !includes

**Comment by Lin4fun** [comment]
Oh sorry, just opend an idea duscussion about this. Havent seen this post from you before.

**Comment by BigBobbas** [comment]
added to todo https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/issues/49
