### ISSUE TITLE
Feature Request: Add Display Activation and Deactivation Based on User Interaction and Idle Period

### ISSUE THREAD

**Issue by scholzri** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#4]
Introduce a feature to automatically enable the display when the red button is touched or the wakeword is detected. Additionally, implement an automatic display deactivation after a predefined idle period.

**Display Activation:**
- Red Button: Enable the display immediately when the red button is touched.
- Wakeword Detection: Enable the display upon detecting a predefined wakeword.

**Display Deactivation:**
- Automatically disable the display after a specified period of inactivity or idle time to conserve power and to make the appearance of the device a little more subtle.

Thank you for considering this feature request!

**Comment by BigBobbas** [comment]
I am releasing a variation of the config soon , which will include a dim 'screen saver' page displaying time and temp. This will timeout to a blank screen after x mins. I am still tidying up instructions and everything else, so it will be a few days before it is ready. I may even be able to incorporate it so that it can be enabled and disabled with a button from the device.

**Comment by BigBobbas** [comment]
I have made an update to include this feature, this can be turned on and off from the 'info' page. I will work on user being able to select a timeout in the next update. This defaults to display time & temp after 30s and then after 3 mins screen turns off.
The ready to use config is s3b.yaml - cheers

**Comment by youkorr** [comment]
bonjour pour la temperature peut on le remplacer par autre thermometre merci est comment??

**Comment by BigBobbas** [comment]
> ![times sensor](https://private-user-images.githubusercontent.com/96953496/338285139-7e338ba0-d78f-474e-830f-986c30e5e984.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNTMwODMsIm5iZiI6MTcxODA1Mjc4MywicGF0aCI6Ii85Njk1MzQ5Ni8zMzgyODUxMzktN2UzMzhiYTAtZDc4Zi00NzRlLTgzMGYtOTg2YzMwZTVlOTg0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDIwNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYjFhM2UyMjUyNWFkMGMwMTc3OGRhY2QwNTFhMDhhYWNlMDVlYmQwYTkyZmExYjczN2YyNzkxMWJiN2UzOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bSN0uBbQWHtox7sakWlx-K36K0_ylFDeYE-b5GCQLt0) hello for the temperature can we replace it with another thermometer thank you how is it??

you would need to add a - homeassistant: sensor and then change this line - 1155 (or near)<br><br>

![image](https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/assets/150487209/29382950-12c1-4b65-a767-fd37499bd3a6)<br>
to the id that you give to the -homeassistant sensor.

**Comment by youkorr** [comment]
Thank you for your answer but as I start is seen your work on this firmware which is beautiful if I understand this you say:
it.printf (160, 180, id (my_fontseg2), light_blue, textalign :: center, "%.F ° C", id (s3temp) .state);

 by that of my temperature sensor:

it.printf (160, 180, id (my_fontseg2), light_blue, textalign :: center, "%.F ° C", id (sensor.temp_entree_temperature) .state);

But I end up with a compilation error need help thank you for the novice :)

**Comment by youkorr** [comment]
Ok I had misread it was necessary to last this line:
You would need to add a - Homeassistant: Sensor
 - Platform: Homeassistant
 ID: Liv_temp
 entity_id: sensor.living_room_temp
 Internal: True

**Comment by BigBobbas** [comment]
you would change to 
```yaml
it.printf (160, 180, id (my_fontseg2), light_blue, textalign :: center, "%.F ° C", id (liv_temp) .state);
```
use lower case for id: 's

**Comment by youkorr** [comment]
it.printf(160, 180, id(my_fontseg2), light_blue, TextAlign::CENTER, "%.f°C", id(liv_temp).state);

Ok thank you it works

**Comment by youkorr** [comment]
For the other functions, taking, air conditioner how they have them id's
![image2](https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/assets/96953496/b7b0b0c5-0929-4bd3-8219-dc53b92edfd3)
![image3](https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/assets/96953496/20d5d1a7-9ecd-4f2d-a714-f79a6778b651)

**Comment by BigBobbas** [comment]
follow the instruction [here](<https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/blob/main/instructions/make%20it%20your%20own.md>)
