### ISSUE TITLE
Audio Playback for Elevenlabs TTS very slow

### ISSUE THREAD

**Issue by cl0ud6uru** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#48]
I'm using elevenlabs for my TTS service and when it plays back on the box speakers it's slow and very low pitched do to the slowness. It plays fine on an external media player. Home assistant cloud TTS sounds fine. 
This issue happens on two different devices. 
I understand this may be out of scope, but has anyone else encountered issues like this?

Thanks!!

**Comment by BigBobbas** [comment]
hi there,
 you can change the sample rate in the following block to match what the tts service you are using uses.
Hope this helps 👍 
![image](https://github.com/user-attachments/assets/ada4d58a-68e8-4452-8c17-f29e87944c7b)

**Comment by cl0ud6uru** [comment]
> hi there, you can change the sample rate in the following block to match what the tts service you are using uses. Hope this helps 👍 ![image](https://private-user-images.githubusercontent.com/150487209/349754529-ada4d58a-68e8-4452-8c17-f29e87944c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MjY4MjIsIm5iZiI6MTcyMTQyNjUyMiwicGF0aCI6Ii8xNTA0ODcyMDkvMzQ5NzU0NTI5LWFkYTRkNThhLTY4ZTgtNDQ1Mi04YzE3LWYyOWU4Nzk0NGM3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQyMjAyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2UwMzg1YWU5MmFlMjVkNTIyNjFkZjNkN2FkODY0MGE1NjQyZjc3MmM1ZDMwYmY0YmQ4OTVlNzViY2RlNGU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5x_pnpP8Sei33XOdPn_6mZdeEqOaxTVApD6hh5ys8zU)

That did the trick!! Thanks for the quick response!

**Comment by Nitroedge** [comment]
For reference also, the Elevenlabs default sample rate is 44100 and I can confirm it works for me also.

**Comment by BigBobbas** [comment]
I have added a variable for this to make it easier to change in upcoming release, including notes of which sample rates to use. Thanks for your feedback 👍
