### ISSUE TITLE
Feature Request: Add continued conversation feature

### ISSUE THREAD

**Issue by scholzri** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#5]
I would like to suggest adding a feature that allows users to continue a conversation with the assistant without repeating the wake-word for a set time interval. This feature would enhance the user experience by enabling more natural and seamless interactions with the assistant especially if something like ChatGPT is used a a conversation agent.

A working implementation of this feature can be found in another custom firmware:
https://github.com/jaymunro/esphome_firmware/blob/continued-conversation/wake-word-voice-assistant/esp32-s3-box-3.yaml#L172

**Benefits:**
- Improved user experience with more natural and fluid conversations
- Reduced need for repetitive wake-word triggering
- Enhanced efficiency in multi-turn interactions

**Comment by BigBobbas** [comment]
Hi , Thank you for your suggestion, this is something that would be Handled by Home Assistant and beyond the scope of this project. This is something I have noticed people requesting similar so hopefully something that someone will pickup and work on.
