### ISSUE TITLE
Add spoken text as sensor

### ISSUE THREAD

**Issue by robgardien** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#50]
I would like te see the text translated with the STT engine to check if the device understood what I said and to display this text on my ulanzi clock :D

**Comment by BigBobbas** [comment]
Hi, 
thank you for the suggestion, I will add this to the todo list 👍 

cheers 

Rob

**Comment by BigBobbas** [comment]
I have now added this feature, you can turn conversation display on and off from the voice settings page 👍 
[Link at the bottom of this announcement](<https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/discussions/44>)

**Comment by BigBobbas** [comment]
added to dev branch sensor and no sensor versions

**Comment by Kelerion-UK** [comment]
compiled and working as expected on the no-sensor.. nice work!

**Comment by BigBobbas** [comment]
cheers buddy , now to just tick off all the other things on my list 🤦 lol ... in between making the most outside whilst it's not raining!!! 🎉

**Comment by robgardien** [comment]
Cheers, thank you!
