### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by JARDALN** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#53]
First please excuse my bad english.
I like this software, unfortunately my HA build is underpowered - RPI4/2GB RAM. A restart will occur during compilation. Would someone be willing to compile my yml file and send me the bin soubour ? Thank you for your time and any response.

**Comment by BigBobbas** [comment]
Hi 
have you tried adding this to your config to the esphome: component near the top?
```yaml
esphome:
  compile_process_limit: 1
```

**Comment by JARDALN** [comment]
Yes, I have this set up. Compilation does not complete, it always ends with a restart. In contrast, maybe an M5 Stack Atom Echo compilation will run, or anything probably less demanding.

**Comment by BigBobbas** [comment]
i can compile this for you. if you can post your config

**Comment by JARDALN** [comment]
Thank you very much. I will prepare my yml file and get back to you.

**Comment by JARDALN** [comment]
I therefore allow myself to attach the yml file after our agreement. Thanks again.

**Comment by JARDALN** [comment]
``

**Comment by BigBobbas** [comment]
> ``

Hi , there is no file attached ?
Regards Rob

**Comment by JARDALN** [comment]
Hello, I had some family concerns.
I can't save the yml file here. Should I rename it or send it to an e-mail?

**Comment by BigBobbas** [comment]
if you could email to support@bbdl.co.uk and i can take a look later this evening  👍

**Comment by JARDALN** [comment]
Sent to email. Thank you.
