### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by JanKraslice** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#84]
Hi, I am using the main version when there is an update release of a new version from your side for example merging main and dev will I need to compile again?

Second question, now I have the main version loaded if I want to try dev is it necessary to compile again and remove the device and add it again after installation? Or just copy and paste.

Thanks

**Comment by BigBobbas** [comment]
Hi there ,
to answer both questions.
yes whenever there is a change this needs to be recompiled to include the changes into the .bin file that is then flashed to the devices as the firmware.
Cheers
Rob

**Comment by BigBobbas** [comment]
closed due to age and no recent update
