### ISSUE TITLE
Crashing during install

### ISSUE THREAD

**Issue by caisamuels** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#89]
I am trying to compile Custom-ESPHome on my 2GB Raspberry Pi 4 but my Home Assistant keeps crashing. I have tried setting `compile_process_limit: 1` but it hasn't made a difference. Is there a way I can compile it on a different device to get around this?

**Comment by BigBobbas** [comment]
Hi you can run ESPHome locally on pretty much any computer.  https://esphome.io/guides/installing_esphome.html
if running on windows it seems to work better on ubuntu using WSL  https://learn.microsoft.com/en-us/windows/wsl/install

if you need any further help please let me know

thanks
Rob

**Comment by BigBobbas** [comment]
closed due to age and no recent update
