### ISSUE TITLE
The ESPHome in progress binary sensor binary_sensor.esp32_s3_box_3_assist_in_progress is deprecated.

### ISSUE THREAD

**Issue by ThirteenTX** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#94]
It looks like we have some time, but all the same, I wanted to get the word out here. Looks like they are changing the current implementation.
![image](https://github.com/user-attachments/assets/be4d6467-5f84-4a0b-bad5-c81285ef9fde)

**Comment by BigBobbas** [comment]
Hi - nothing to worry about - this is only on the HA side of things.
HA adds the entity 'assist in progress' to all ESPHome VA devices,, this has now changed to a sensor with multiple states, which will give better clarity to what state the 'VA' is currently in.
Clicking submit is all that you need to do. 
If you had any automations in HA using 'assist in progress' as a trigger , you would need to update these. 

Cheers
Rob 👍

**Comment by BigBobbas** [comment]
closed due to age and no recent update
